In [ ]:
1. Write a Python Program to Add Two Matrices?
2. Write a Python Program to Multiply Two Matrices?
3. Write a Python Program to Transpose a Matrix?
4. Write a Python Program to Sort Words in Alphabetic Order?
5. Write a Python Program to Remove Punctuation From a String?

In [1]:
import numpy as np

In [11]:
# 1. Write a Python Program to Add Two Matrices?
mat1=np.matrix([[1,2],[1,2]])
mat2=np.matrix([[1,2],[1,2]])
print("matrix addition  is \n",mat1+mat2)

matrix addition  is 
 [[2 4]
 [2 4]]


In [6]:
# 1. Write a Python Program to Add Two Matrices? using nested list 

row=int(input("enter the number of rows : "))
col=int(input("enter the number of columns : "))
mat1=[]
mat2=[]
r=[]
c=[]
for i in range(row):    
    for j in range(col):
        r.append(int(input()))
    mat1.append(r)
    r=[]
print(mat1)
print()
print("matrix1 is :: ")
for i in range(row):    
    for j in range(col):
        print(mat1[i][j],end=" ")
    print()
#print(mat1)

print()
print("enter the elements of second matrix ::")
print()
for i in range(row):    
    for j in range(col):
        c.append(int(input()))
    mat2.append(c)
    c=[]
print(mat2)
print()
print("matrix2 is :: ")

for i in range(row):    
    for j in range(col):
        print(mat2[i][j],end=" ")
    print()
#print(mat2)

result = []
re=[]
for i in range(row):    
    for j in range(col):
        re.append(0)
    result.append(re)
    re=[]
print(result)
print()
 #addition of matrices 

for i in range(row):    
    for j in range(col):
        result[i][j]=mat1[i][j]+mat2[i][j]
        
        #final.append(res)
print("the final matrix is :: \n")
for i in range(row):    
    for j in range(col):
        print(result[i][j],end=" ")
    print()        
        



enter the number of rows : 2
enter the number of columns : 2
1
2
3
4
[[1, 2], [3, 4]]

matrix1 is :: 
1 2 
3 4 

enter the elements of second matrix ::

5
6
7
8
[[5, 6], [7, 8]]

matrix2 is :: 
5 6 
7 8 
[[0, 0], [0, 0]]

the final matrix is :: 

6 8 
10 12 


In [9]:
# 2. Write a Python Program to Multiply Two Matrices?
mat1=np.matrix([[1,2],[1,2]])
mat2=np.matrix([[1,2],[1,2]])
print("matrix multiplication is ",mat1*mat2)

matrix([[3, 6],
        [3, 6]])

In [10]:
# 2. Write a Python Program to Multiply Two Matrices? #using nested list 

row=int(input("enter the number of rows : "))
col=int(input("enter the number of columns : "))
mat1=[]
mat2=[]
r=[]
c=[]
for i in range(row):    
    for j in range(col):
        r.append(int(input()))
    mat1.append(r)
    r=[]
print(mat1)
print()
print("matrix1 is :: ")
for i in range(row):    
    for j in range(col):
        print(mat1[i][j],end=" ")
    print()
#print(mat1)

print()
print("enter the elements of second matrix ::")
print()
for i in range(row):    
    for j in range(col):
        c.append(int(input()))
    mat2.append(c)
    c=[]
print(mat2)
print()
print("matrix2 is :: ")

for i in range(row):    
    for j in range(col):
        print(mat2[i][j],end=" ")
    print()
#multiplication 
result = []
re=[]
for i in range(row):    
    for j in range(col):
        re.append(0)
    result.append(re)
    re=[]
print(result)
print()

for i in range(row):    
    for j in range(col):
        for k in range(col):
            result[i][j] += mat1[i][k] * mat2[k][j]
print()
print("the multiplication of above matrices is :\n")
for i in range(row):    
    for j in range(col):
        print(result[i][j],end=" ")
    print()     
            

enter the number of rows : 2
enter the number of columns : 2
1
2
3
4
[[1, 2], [3, 4]]

matrix1 is :: 
1 2 
3 4 

enter the elements of second matrix ::

5
6
7
8
[[5, 6], [7, 8]]

matrix2 is :: 
5 6 
7 8 
[[0, 0], [0, 0]]


the multiplication of above matrices is :

19 22 
43 50 


In [19]:
# 3. Write a Python Program to Transpose a Matrix?
mat1=np.matrix([[1,2],[3,4]])
print("matrix before transpose is \n ",mat1)
trans = mat1.T
print()
print("the transpose of a matrix is \n ",trans)

matrix before transpose is 
  [[1 2]
 [3 4]]

the transpose of a matrix is 
  [[1 3]
 [2 4]]


In [5]:
# 3. Write a Python Program to Transpose a Matrix? using nested list 
row=int(input("enter the number of rows : "))
col=int(input("enter the number of columns : "))
mat1=[]
r=[]

for i in range(row):    
    for j in range(col):
        r.append(int(input()))
    mat1.append(r)
    r=[]
print(mat1)
print()
print("matrix1 is :: ")
for i in range(row):    
    for j in range(col):
        print(mat1[i][j],end=" ")
    print()
    
print()
print("transpose of the matrix is ")
print()
for i in range(row):    
    for j in range(col):
        print(mat1[j][i],end=" ")
    print()

enter the number of rows : 3
enter the number of rows : 3
1
2
3
4
5
6
7
8
9
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

matrix1 is :: 
1 2 3 
4 5 6 
7 8 9 

transpose of the matrix is 

1 4 7 
2 5 8 
3 6 9 


In [27]:
# 4. Write a Python Program to Sort Words in Alphabetic Order?

a=input("enter the words :: ")
b=a.split()
b.sort()
print(b)

enter the words :: Python Program to Sort Words in Alphabetic Order
['Alphabetic', 'Order', 'Program', 'Python', 'Sort', 'Words', 'in', 'to']


In [25]:
# 5. Write a Python Program to Remove Punctuation From a String?

punc= '''!"#$%&'()*+,-./:;?@[\]^_`{|}~'''
passage =input("enter the passage :: ")
for i in passage:
    for i in  punc :
        passage=passage.replace(i,'')
print("after removing punctuations :: ",passage)

     
        

enter the passage :: hi@ all! ho@w 'ar$e y(o)u
after removing punctuations ::  hi all how are you
